config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :recipes

  root "foods#index"

  resources :public_recipes
  # resources :recipe_foods

  resources :foods

  resources :recipes, only: [:index, :show, :new, :create, :destroy] do
    resources :recipe_foods, only: [:new, :create, :destroy, :update, :edit]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/food.rb
class Food < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  belongs_to :user
  has_many :recipe_foods, dependent: :destroy
  has_many :foods, through: :recipe_foods
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe
  belongs_to :food
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :bio, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :bio, :email, :password, :password_confirmation, :current_password)
    end
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /foods or /foods.json
  def index
    @foods = Food.all
  end

  # GET /foods/1 or /foods/1.json
  def show; end

  # GET /foods/new
  def new
    @food = Food.new
  end

  # GET /foods/1/edit
  def edit; end

  # POST /foods or /foods.json
  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    respond_to do |format|
      if @food.save
        format.html { redirect_to root_path, notice: 'Food was successfully created.' }
        format.json { render :show, status: :created, location: @food }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /foods/1 or /foods/1.json
  def update
    respond_to do |format|
      if @food.update(food_params)
        format.html { redirect_to food_url(@food), notice: 'Food was successfully updated.' }
        format.json { render :show, status: :ok, location: @food }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @food.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foods/1 or /foods/1.json
  def destroy
    @food.destroy

    respond_to do |format|
      format.html { redirect_to foods_url, notice: 'Food was successfully deled.' }

      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_food
    @food = Food.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  before_action :authenticate_user!

  def index
    @recipes = Recipe.where(public: true)
    @price = find_price
  end

  def find_price
    price = 0
    recipe = Recipe.first
    recipe.foods.map { |rec| price += rec.price }
    price
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  before_action :authenticate_user!

  def new
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.new
  end

  def create
    @recipe = Recipe.find(params[:recipe_id])
    @recipe_food = @recipe.recipe_foods.create(recipe_foods_params)
    if @recipe_food.save
      flash[:notice] = 'Food created sucessfully.'
      redirect_to @recipe
    else
      render :new
    end
  end

  def edit
    @recipe_food = RecipeFood.find(params[:id])
  end

  def update
    @recipe_food = RecipeFood.find(params[:id])
    if @recipe_food.update(recipe_foods_params)
      flash[:success] = 'Recipe Food updated successfully.'
    else
      flash[:error] = 'Could not add'
    end
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  def destroy
    @recipe_food = RecipeFood.find(params[:id])
    @recipe_food.destroy
    flash[:success] = 'Recipe Food deleted successfully.'
    redirect_to recipe_path(@recipe_food.recipe_id)
  end

  private

  def recipe_foods_params
    params.require(:recipe_food).permit(:quantity, :food_id)
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /recipes or /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1 or /recipes/1.json
  def show; end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit; end

  # POST /recipes or /recipes.json
  def create
    @recipe = Recipe.new(recipe_params)
    @recipe.user_id = current_user.id

    respond_to do |format|
      if @recipe.save
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1 or /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to recipe_url(@recipe), notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recipes/1 or /recipes/1.json
  def destroy
    @recipe.destroy

    respond_to do |format|
      format.html { redirect_to recipes_url, notice: 'Recipe was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_recipe
    @recipe = Recipe.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description, :public, :user_id)
  end
end

app/controllers/turbo_devise_controller.rb
class TurboDeviseController < ApplicationController
  class Responder < ActionController::Responder
    def to_turbo_stream
      controller.render(options.merge(formats: :html))
    rescue ActionView::MissingTemplate => e
      raise e if get?

      has_errors? && default_action
      render rendering_options.merge(formats: :html, status: :unprocessable_entity)
    else
      redirect_to navigation_location
    end
  end

  self.responder = Responder
  respond_to :html, :turbo_stream
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
 
<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Food</th>
      <th scope="col">Measurement unit</th>
      <th scope="col">Unit price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th scope="row">1</th>
      <td><%= food.name %></td>
      <td><%= food.measurement_unit %></td>
      <td><%= food.price %></td>
      <td><%= link_to "Delete" %></td>
    </tr>
  </tbody>
</table>
</div>

app/views/foods/_form.html.erb
<%= form_with(model: food) do |form| %>
    <% if food.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(food.errors.count, "error") %> prohibited this food from being saved:</h2>
  
        <ul>
          <% food.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div>
      <%= form.label :name, style: "display: block" %>
      <%= form.text_field :name %>
    </div>
  
    <div>
      <%= form.label :measurement_unit, style: "display: block" %>
      <%= form.text_field :measurement_unit %>
    </div>
  
    <div>
      <%= form.label :price, style: "display: block" %>
      <%= form.text_field :price %>
    </div>
  
    <div>
      <%= form.label :quantity, style: "display: block" %>
      <%= form.number_field :quantity %>
    </div>
  
    <div>
      <%= form.submit %>
    </div>
  <% end %>
  

app/views/foods/index.html.erb
<p style="color: green"><%= notice %></p>

<div class= "d-flex">

<h1>Foods</h1>
<p  class= 'ms-auto'>
<%= link_to new_food_path, :class => "btn btn-outline-dark add mb-3" do %> Add food 
  <% end %>

</p>
</div>

<table class="table">
  <thead>
    <tr>
      <th scope="col"></th>
      <th scope="col">Food</th>
      <th scope="col">Measurement unit</th>
      <th scope="col">Unit price</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
  <% @foods.each do |food| %>
    <tr>
      <th scope="row"><%= food.id %></th>
      <td><%= food.name %></td>
      <td><%= food.measurement_unit %></td>
      <td><%= food.price %></td>
      <td><%= link_to "Delete", food_path(food),  data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></td>
    </tr>
  <% end %>
    
  </tbody>
  </table>

app/views/foods/new.html.erb
<h1>New food</h1>

<%= render "form", food: @food %>

<br>

<div>
  <%= link_to "Back to foods", foods_path %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Edit this food", edit_food_path(@food) %> |
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Delete this food", @food, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Blog App with Rals demo</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <header>
    <%= render 'navbar/header' %>
    </header>

    <main>
    <div class="container">
    <%= yield %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
    </div>
    </main>
  </body>
</html>

app/views/navbar/_header.html.erb
<nav class="navbar navbar-expand-lg bg-dark">
  <div class="container-fluid">
  <%= link_to 'Home', root_path, class: "navbar-brand text-white" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Recipes', recipes_path, class: "nav-link active text-white" %>
        </li>
        <li class="nav-item">
        <%= link_to 'Public Recipes', public_recipes_path, class: "nav-link active text-white" %>
        </li>
      </ul>
      <% if user_signed_in? %>
    <%= button_to t('sign_out'), destroy_user_session_path, method: :delete, class:"btn btn-outline-danger" %>
    <% end %>
    </div>
  </div>
</nav>

app/views/public_recipes/index.html.erb
<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet">
<link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="stylesheet">
<title>Bootstrap Example</title>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
</head>
<p style="color: green"><%= notice %></p>

<h1 class= "public title">Public recipes</h1>
<% @recipes.each do |recipe| %>
<div class="row g-0 text-center">
    <div class="col-sm-6 col-md-8">
      <h1>
        <%= link_to recipe.name, recipe, class: "recipetitle" %>
        </h1>
      <p> By:
      <%= recipe.user.name %>
      </p>       
        </div>

        <div class="col-6 col-md-4">
          <p>
            Total food items: <%= recipe.foods.length %>
          </p>
          <p>
            Total price: <%= @price %>
          </p>  
        
        </div>
        </div>
        <% end %>

app/views/recipe_foods/edit.html.erb
<h2 class="heading">Edit Recipe Food</h2>
<div>
<%= form_with  model: @recipe_food, url: { action: "update"}, local: true, class:"input-form"  do |f|%>
    <div class="form-div" >

    <div class="mb-3 col-sm-8">
    <%= f.label :food, class:"form-label" %><br>
    <%= f.select :food_id, Food.all.collect {|food| [food.name, food.id]},{ include_blank: true} , class:"form-select" %><br>
    </div>

    <div class="mb-3 col-sm-8">
    <%= f.label :quantity, class:"form-label" %><br>
    <%= f.text_field :quantity ,  class:"form-control" , required: true, min:1%><br>
    </div>

    <div class="mb-3 col-sm-2">
    <%= f.submit "Update Recipe_Food", class:"btn btn-primary form-control" %>
    </div>
    </div>
<%end%>
<div class="form-div" >
  <div class="mb-3 col-sm-2">
    
        <%=link_to 'Back', foods_path, class:"btn btn-primary form-control"%>
  </div>
</div>
</div>

app/views/recipe_foods/new.html.erb
<h4>Add Recipe Food</h4>
<%= form_with model: [@recipe, @recipe.recipe_foods.create] do |form|%>
<div class="mb-3">
  <%= form.label :food %>
  <div>
    <%= form.select :food_id, Food.all.collect {|food| [food.name, food.id]},{
    include_blank: true} , class:"form-select" %>
  </div>
</div>
<div class="mb-3">
  <%= form.label :quantity %>
  <div>
    <%= form.number_field :quantity , class:"form-control" , required: true,
    placeholder: '1', min: 1%>
  </div>
</div>

<div class="mb-3"><%= form.submit "Add", class:"btn btn-dark" %></div>
<%end%>
<div class="mb-3">
  <%=link_to 'Return to Recipes', recipe_path(@recipe.id), class:"btn btn-link"%>
</div>

app/views/recipes/_form.html.erb
<%= form_with(model: recipe) do |form| %>
  <% if recipe.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
        <% recipe.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :preparation_time, style: "display: block" %>
    <%= form.text_field :preparation_time %>
  </div>

  <div>
    <%= form.label :cooking_time, style: "display: block" %>
    <%= form.text_field :cooking_time %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :public, style: "display: block" %>
    <%= form.check_box :public %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/recipes/_recipe.html.erb
<div id="<%= dom_id recipe %>">
  <p>
    <strong>Name:</strong>
    <%= recipe.name %>
  </p>

  <p>
    <strong>Preparation time:</strong>
    <%= recipe.preparation_time %>
  </p>

  <p>
    <strong>Cooking time:</strong>
    <%= recipe.cooking_time %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= recipe.description %>
  </p>

  <p>
    <strong>Public:</strong>
    <%= recipe.public %>
  </p>

  <p>
    <%= button_to 'Generate Shopping list' %>
  </p>

  <p>
    <%= button_to 'Add ingredients' %>
  </p>

  <% recipe.user.foods.each do |recipe| %>
      <p> food name: <%= recipe.name %> </p>
      <p> quantty: <%= recipe.quantity %> </p>
      <p> value: <%= recipe.price %> </p>
    <% end %>

</div>

app/views/recipes/edit.html.erb
<h1>Editing recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Show this recipe", @recipe %> |
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="application">
    <link href="https://getbootstrap.com/docs/5.2/assets/css/docs.css" rel="application">
    <title>Bootstrap Example</title>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
  </head>
<p style="color: green"><%= notice %></p>

<h1 class= "recipes title">Recipes</h1>
<% @recipes.each do |recipe| %>
<div class="row g-0 text-center">
    <div class="col-sm-6 col-md-8">
      <h1>
        <%= link_to recipe.name, recipe, class: "recipetitle" %>
      </h1>
      <%= link_to "REMOVE", recipe_path(recipe),  data: {
        turbo_method: :delete,
        turbo_confirm: "Are you sure?"
        } %>
        </div>
        <%= recipe.description %>

        </div>
        <% end %>
        <%= link_to "Add New Recipe", new_recipe_path, class: "title" %>

app/views/recipes/new.html.erb
<h1>New recipe</h1>

<%= render "form", recipe: @recipe %>

<br>

<div>
  <%= link_to "Back to recipes", recipes_path %>
</div>

app/views/recipes/show.html.erb
<div class="border border-1 border-dark rounded p-4">
  <div class="d-flex flex-column">
    <div class="d-flex justify-content-between align-items-center mb-3">
      <h4 class><%= @recipe.name%></h4>
      <div class="public-btn">
        <% if @recipe.public %>
        <div class="form-check form-switch">
          <input
            class="form-check-input"
            type="checkbox"
            id="flexSwitchCheckChecked"
            checked
          />
          <label class="form-check-label" for="flexSwitchCheckChecked"
            >Public</label
          >
        </div>
        <% end %> 
        <% if !@recipe.public %>
        <div class="form-check form-switch">
          <input
            class="form-check-input"
            type="checkbox"
            id="flexSwitchCheckChecked"
          />
          <label class="form-check-label" for="flexSwitchCheckChecked"
            >Public</label
          >
        </div>
        <% end %>
      </div>
    </div>
    <p class="text-bold">
      Cooking Time:
      <span class="fw-bold"><%= @recipe.cooking_time %> min(s)</span>
    </p>
    <p class="text-bold">
      Preparation Time:
      <span class="fw-bold"><%= @recipe.preparation_time %> min(s)</span>
    </p>
    <div>
      <p class="fw-bold mb-0">Steps:</p>
      <p class="text-muted lh-base"><%= @recipe.description %></p>
    </div>
  </div>
  <div class="d-flex justify-content-between">
      <button type = "button" class= "btn btn-dark bg-dark add mb-3" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        Generate shopping list
      </button>
      <%= link_to new_recipe_recipe_food_path(@recipe), :class => "btn btn btn-outline-dark add mb-3" do %> Add Ingredients 
    <% end %>
  </div>
  <hr class="my-1" />
  <table class="table container rounded">
    <thead>
      <tr>
        <th scope="col">Food</th>
        <th scope="col">Quantity</th>
        <th scope="col">Value</th>
        <th scope="col"></th>
      </tr>
    </thead>
    <tbody>
      <% @recipe.recipe_foods.each do |recipeFood|%> 
      <tr>
        <td><%= recipeFood.food.name%></th>
        <td><%= recipeFood.quantity %><% recipeFood.food.measurement_unit  %></td>
        <td>$<%= recipeFood.quantity.to_i * recipeFood.food.price %></td>
          <td class="d-flex gap-3 justify-content-end">
            <%=button_to "Delete", recipe_recipe_food_path(recipe_id: @recipe.id, id: recipeFood.id), method: :delete, class:"btn btn-danger"%>
            <%=link_to "Modify", edit_recipe_recipe_food_path(recipe_id: @recipe.id, id:recipeFood.id), class:"btn btn-dark"%>
          </td>
     
      </tr>
      <% end %>
    </tbody>
  </table>
</div>